config/routes.rb
Rails.application.routes.draw do
  resources :replies do
    member do
      put "like", to: "replies#upvote"
    end
  end
  
  resources :submissions  do
    member do
      put "like", to: "submissions#upvote"
    end
  end
  
  resources :comments do
    member do
      put "like", to: "comments#upvote"
    end
  end  
    
  resources :users 
  
  get '/auth/:provider/callback', to:'sessions#create'
  
  root 'submissions#index'
  
  
  
  scope '/api', defaults: {format: :json} do
    scope '/submissions' do
      get '/' => 'api/submissions#index'
      post '/' => 'api/submissions#create'
      get '/ask' => 'api/submissions#ask'
      get '/links' => 'api/submissions#links'
      scope '/:id' do
        get '/' => 'api/submissions#show'
        get '/comments' => 'api/submissions#comments'
        delete '/' => 'api/submissions#delete'
        put '/vote' => 'api/submissions#upvote'
      end
    end
    scope '/comments' do
      get '/' => 'api/comments#index'
      post '/' => 'api/comments#create'
      scope '/:id' do
        get '/' => 'api/comments#show'
        get '/replies' => 'api/comments#replies'
        put '/vote' => 'api/comments#upvote'
      end
    end
    scope '/users' do
      get '/' => 'api/users#index'
      scope '/:id' do
        get '/' => 'api/users#show'
        put '/' => 'api/users#edit'
        get '/submissions' => 'api/users#submissions'
        get '/comments' => 'api/users#comments'
        get '/replies' => 'api/users#replies'
      end
    end
    scope '/replies' do
      get '/' => 'api/replies#index'
      post '/' => 'api/replies#create'
      scope '/:id' do
        get '/' => 'api/replies#show'
        put '/vote' => 'api/replies#upvote'
      end
    end
  end
  

end

app/models/reply.rb
class Reply < ActiveRecord::Base
    belongs_to :user
    acts_as_votable
    belongs_to :comment
    validates :content, presence: true
    after_initialize :set_default_values
    def set_default_values
        self.points ||= 0
    end
end

app/controllers/api/replies_controller.rb
module API
    class RepliesController < ApplicationController
        skip_before_action :verify_authenticity_token
       
        def index
            @replies = Reply.all
            respond_to do |format|
                format.xml { render xml: @replies }
                format.json { render json: @replies }
            end
        end
        
        def create
            @content = params["content"]
            @comment_id = params["comment_id"]
            @reply = Reply.new(:content => @content, :points => 0, :user_id => 1, :comment_id => @comment_id)
            respond_to do |format|
                if @reply.save
                  format.json { render json: @reply }
                  format.xml { render xml: @reply }
                else
                  format.json { render json: @reply.errors, status: :unprocessable_entity }
                  format.xml { render xml: @reply.errors, status: :unprocessable_entity }
                end
            end
        end
            
        def show
            @reply = Reply.find(params[:id])
            respond_to do |format|
                format.xml { render xml: @reply }
                format.json { render json: @reply }
            end
            rescue ActiveRecord::RecordNotFound
                render json: '{"response": "reply not found"}', :status => 404
        end    
        
        def upvote
            @reply = Reply.find(params[:id])
            @reply.points += 1
            respond_to do |format|
                if @reply.save
                    format.json { render json: @reply }
                    format.xml { render xml: @reply }
                else
                    format.json { render json: @reply.errors, status: :unprocessable_entity }
                    format.xml { render xml: @reply.errors, status: :unprocessable_entity }
                end
            end
            rescue ActiveRecord::RecordNotFound
                render json: '{"response": "reply not found"}', :status => 404
        end
    end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :set_reply, only: [:show, :edit, :update, :destroy]

  def upvote 
    @reply = Reply.find(params[:id])
    @reply.upvote_by current_user
    redirect_to :back
  end  

  # GET /replies
  # GET /replies.json
  def index
    @replies = Reply.all
  end

  # GET /replies/1
  # GET /replies/1.json
  def show
  end

  # GET /replies/new
  def new
    @reply = Reply.new
    @comment = Comment.find(params[:com_id])
  end

  # GET /replies/1/edit
  def edit
  end

  # POST /replies
  # POST /replies.json
  def create
    @reply = Reply.new(reply_params)
    @comment = Comment.find(@reply.comment_id)

    respond_to do |format|
      if @reply.save
        format.html { redirect_to submissions_path+"/"+@comment.submission_id.to_s,
          notice: 'Reply was successfully created.' }
        format.json { render :show, status: :created, location: @reply }
      else
        format.html { render :new }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /replies/1
  # PATCH/PUT /replies/1.json
  def update
    respond_to do |format|
      if @reply.update(reply_params)
        format.html { redirect_to @reply, notice: 'Reply was successfully updated.' }
        format.json { render :show, status: :ok, location: @reply }
      else
        format.html { render :edit }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /replies/1
  # DELETE /replies/1.json
  def destroy
    @reply.destroy
    respond_to do |format|
      format.html { redirect_to replies_url, notice: 'Reply was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reply
      @reply = Reply.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reply_params
      params.require(:reply).permit(:content, :points, :user_id, :comment_id)
    end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/replies/_form.html.erb
<%= form_for(@reply) do |f| %>
  <% if @reply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reply.errors.count, "error") %> prohibited this reply from being saved:</h2>

      <ul>
      <% @reply.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <input type="hidden" name="reply[user_id]" value="<%= current_user.id %>" />
  <input type="hidden" name="reply[comment_id]" value="<%= @comment.id %>" />
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/replies/edit.html.erb
<h1>Editing Reply</h1>

<%= render 'form' %>

<%= link_to 'Show', @reply %> |
<%= link_to 'Back', replies_path %>

app/views/replies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Replies</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Points</th>
      <th>User</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @replies.each do |reply| %>
      <tr>
        <td><%= reply.content %></td>
        <td><%= reply.points %></td>
        <td><%= reply.user %></td>
        <td><%= reply.comment %></td>
        <td><%= link_to 'Show', reply %></td>
        <td><%= link_to 'Edit', edit_reply_path(reply) %></td>
        <td><%= link_to 'Destroy', reply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reply', new_reply_path %>

app/views/replies/new.html.erb
<div class="submission">
    <div class="menu-superior">
        <%= link_to 'Hacker News', submissions_path %>
        <div class="right-text">
          <% if current_user %>
            Logged as <%= link_to current_user.userName , current_user%>
          <% else %>
            <%= link_to 'Log In', root_path + "/auth/twitter"%>
          <% end %>
        </div>
    </div>
    <div class="content">
        <div class="special-text">
            <%= @comment.user.userName %>
            <%= @comment.created_at.to_formatted_s(:short) %>
        </div>
        <br>
        
        <%= @comment.content %>
        <%= render 'form' %>
        
        <%= link_to submissions_path+"/"+@comment.submission_id.to_s  , :class => "btn" do %>
            Back
        <% end %>
    </div>
</div>

app/views/replies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @reply.content %>
</p>

<p>
  <strong>Points:</strong>
  <%= @reply.points %>
</p>

<p>
  <strong>User:</strong>
  <%= @reply.user.userName %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @reply.comment %>
</p>

<%= link_to 'Edit', edit_reply_path(@reply) %> |
<%= link_to 'Back', replies_path %>