config/routes.rb
Rails.application.routes.draw do
  resources :replies do
    member do
      put "like", to: "replies#upvote"
    end
  end
  
  resources :submissions  do
    member do
      put "like", to: "submissions#upvote"
    end
  end
  
  resources :comments do
    member do
      put "like", to: "comments#upvote"
    end
  end  
    
  resources :users 
  
  get '/auth/:provider/callback', to:'sessions#create'
  
  root 'submissions#index'
  
  
  
  scope '/api', defaults: {format: :json} do
    scope '/submissions' do
      get '/' => 'api/submissions#index'
      post '/' => 'api/submissions#create'
      get '/ask' => 'api/submissions#ask'
      get '/links' => 'api/submissions#links'
      scope '/:id' do
        get '/' => 'api/submissions#show'
        get '/comments' => 'api/submissions#comments'
        delete '/' => 'api/submissions#delete'
        put '/vote' => 'api/submissions#upvote'
      end
    end
    scope '/comments' do
      get '/' => 'api/comments#index'
      post '/' => 'api/comments#create'
      scope '/:id' do
        get '/' => 'api/comments#show'
        get '/replies' => 'api/comments#replies'
        put '/vote' => 'api/comments#upvote'
      end
    end
    scope '/users' do
      get '/' => 'api/users#index'
      scope '/:id' do
        get '/' => 'api/users#show'
        put '/' => 'api/users#edit'
        get '/submissions' => 'api/users#submissions'
        get '/comments' => 'api/users#comments'
        get '/replies' => 'api/users#replies'
      end
    end
    scope '/replies' do
      get '/' => 'api/replies#index'
      post '/' => 'api/replies#create'
      scope '/:id' do
        get '/' => 'api/replies#show'
        put '/vote' => 'api/replies#upvote'
      end
    end
  end
  

end

app/models/submission.rb
class Submission < ActiveRecord::Base
    belongs_to :user
    acts_as_votable
    has_many :comments
    validates :title, presence: true
    
    validates :content, presence: true, if: "url.blank?"
    validates :url, presence: true, if: "content.blank?"
    validates :content, presence: false, if: "!url.blank?"
    validates :url, presence: false, if: "!content.blank?"
    
    after_initialize :set_default_values
    def set_default_values
        self.points ||= 0
    end
end

app/controllers/api/submissions_controller.rb
module API
    class SubmissionsController < ApplicationController

        skip_before_action :verify_authenticity_token
        
        def index
            @submissions = Submission.all
            respond_to do |format|
                format.xml { render xml: @submissions.order('updated_at desc') }
                format.json { render json: @submissions.order('updated_at desc') }
            end
        end
        
        def ask
            @submissions = Submission.where(url: [nil, ""])
            respond_to do |format|
                format.xml { render xml: @submissions.order('updated_at desc') }
                format.json { render json: @submissions.order('updated_at desc') }
            end
        end
        
        def links
            @submissions = Submission.where(content: [nil, ""])
            respond_to do |format|
                format.xml { render xml: @submissions.order('updated_at desc') }
                format.json { render json: @submissions.order('updated_at desc') }
            end
        end
        
        def create
            @title = params["title"]
            @url = params["url"]
            @content = params["content"]
            if ((@url == nil and @content != nil) or (@url != nil and @content == nil))
                @submission = Submission.new(:title => @title, :url => @url, :content => @content, :points => 0, :user_id => 1)
                respond_to do |format|
                    if @submission.save
                      format.json { render json: @submission }
                      format.xml { render xml: @submission }
                    else
                      format.json { render json: @submission.errors, status: :unprocessable_entity }
                      format.xml { render xml: @submission.errors, status: :unprocessable_entity }
                    end
                end
            else
                render json: '{"response": "content or url"}', :status => 400
            end
        end
        
        def delete
           # http://stackoverflow.com/questions/23927314/rails-render-xml
            @submission = Submission.find(params[:id])
            respond_to do |format|
                @comments = @submission.comments
                if @submission.destroy
                    @comments.each do |comment|
                        comment.replies.each do |reply|
                            reply.destroy
                        end
                        comment.destroy
                    end
                    format.json { render json: '{"response": "succesfully deleted"}' }
                    format.xml { render xml:"<response>succesfully deleted</response>" }
                end
            end
            rescue ActiveRecord::RecordNotFound
                render json: '{"response": "submission not found"}', :status => 404
        end
        
        #@submission.comments.each do |comment|
        

        def show
            @submission = Submission.find(params[:id])
            respond_to do |format|
                format.xml { render xml: @submission }
                format.json { render json: @submission }
            end
            rescue ActiveRecord::RecordNotFound
                render json: '{"response": "submission not found"}', :status => 404
        end
        
        def comments
           @submission = Submission.find(params[:id])
           respond_to do |format|
                format.xml { render xml: @submission.comments }
                format.json { render json: @submission.comments }
            end
            rescue ActiveRecord::RecordNotFound
                render json: '{"response": "submission not found"}', :status => 404
        end
        
        def upvote
            @submission = Submission.find(params[:id])
            @submission.points += 1
            respond_to do |format|
                if @submission.save
                    format.json { render json: @submission }
                    format.xml { render xml: @submission }
                else
                    format.json { render json: @submission.errors, status: :unprocessable_entity }
                    format.xml { render xml: @submission.errors, status: :unprocessable_entity }
                end
            end
            rescue ActiveRecord::RecordNotFound
                render json: '{"response": "submission not found"}', :status => 404
        end
    end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: [:show, :edit, :update, :destroy]

  def upvote
    @submission = Submission.find(params[:id])
    @submission.upvote_by current_user
    redirect_to :back
  end

  # GET /submissions
  # GET /submissions.json
  def index
    @submissions = Submission.all
    @isAsk = false
  end

  # GET /submissions/1
  # GET /submissions/1.json
  def show
    @comment = Comment.new
  end

  # GET /submissions/new
  def new
    @submission = Submission.new
  end

  # GET /submissions/1/edit
  def edit
  end

  # POST /submissions
  # POST /submissions.json
  def create
    @submission = Submission.new(submission_params)
    if (@submission.url != "" and @submission.content != "")
      redirect_to :back
    else
      respond_to do |format|
        if @submission.save
          format.html { redirect_to @submission, notice: 'Submission was successfully created.' }
          format.json { render :show, status: :created, location: @submission }
        else
          format.html { render :new }
          format.json { render json: @submission.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /submissions/1
  # PATCH/PUT /submissions/1.json
  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to @submission, notice: 'Submission was successfully updated.' }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1
  # DELETE /submissions/1.json
  def destroy
    @submission.destroy
    respond_to do |format|
      format.html { redirect_to submissions_url, notice: 'Submission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      @submission = Submission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submission_params
      params.require(:submission).permit(:title, :url, :points, :content, :user_id)
    end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/submissions/_form.html.erb
<%= form_for(@submission) do |f| %>
  <% if @submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
      <% @submission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <h5>OR</h5>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <input type="hidden" name="submission[user_id]" value="<%= current_user.id %>" />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/submissions/edit.html.erb
<div class="submission">
  <div class="menu-superior">
    <%= link_to 'Hacker News', submissions_path %>
    <div class="right-text">
      <% if current_user %>
        Logged as <%= link_to current_user.userName , current_user%>
      <% else %>
        <%= link_to 'Log In', root_path + "/auth/twitter"%>
      <% end %>
    </div>
  </div>
      <div class="content">
          <h4>Editing Submission</h4>

            <%= render 'form' %>
            
            <%= link_to submissions_path  , :class => "btn" do %>
                Back
            <% end %>
      </div>
    </div>
</div>

app/views/submissions/index.html.erb
<div class="submission">
  <div class="menu-superior">
    <%= link_to 'Hacker News', submissions_path %>
    <div class="left-text">
      <% if current_user %>
        <%= link_to 'Submit', new_submission_path %> |
      <%end%>
      <%= link_to "Ask", submissions_path + '?ask=true'%>
    </div>
    <div class="right-text">
      <% if current_user %>
        Logged as <%= link_to current_user.userName , current_user%>
      <% else %>
        <%= link_to 'Log In', "/auth/twitter"%>
      <% end %>
    </div>
  </div>
  <div class= "content">
  
    <ul>
    <!-- LINKS -->
    <% if !current_page?(ask: 'true')  %>
      <% @submissions.order('created_at desc').each do |submission| %>
        <li>
          <%= link_to "", like_submission_path(submission), method: :put , :class => "upvote" %>
          <div class="special-text">
            <% if submission.url != "" %>
              <a href=<%= submission.url %> target="_blank"><%= submission.title %></a>
              (<%= submission.url %>)
            <% else %>
              <%= link_to submission.title, submission %>
            <% end %>
            <br>
            <%= submission.get_upvotes.size%> points
            by <%= link_to submission.user.userName, submission.user %>
            <%= submission.created_at.to_formatted_s(:short) %>
            <%= link_to "#{submission.comments.size} comments", submission %>
            
            <% if current_user == submission.user %>
              <%= link_to 'Edit', edit_submission_path(submission) %>
              <%= link_to 'Remove', submission, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
            
          </div>
        </li>
      <% end %>
    <% end %>
    
    <!-- PREGUNTES -->
    <% if current_page?(ask: 'true')  %>
      <% @submissions.order('created_at desc').each do |submission| %>
        <% if submission.content != "" %>
          <li>
            <%= link_to "", like_submission_path(submission), method: :put , :class => "upvote" %>
            <div class="special-text">
              <%= link_to submission.title, submission %>
              <br>
              <%= submission.get_upvotes.size%> points
              by <%= link_to submission.user.userName, submission.user %>
              <%= submission.created_at.to_formatted_s(:short) %>
              <%= link_to "#{submission.comments.size} comments", submission %>
              
              <% if current_user == submission.user %>
                <%= link_to 'Edit', edit_submission_path(submission) %>
                <%= link_to 'Remove', submission, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            </div>
          </li>
        <% end %>
      <% end %>
    <% end %>
    
    </ul>
  </div>
</div>

app/views/submissions/new.html.erb
<div class="submission">
  <div class="menu-superior">
    <%= link_to 'Hacker News', submissions_path %>
    <div class="right-text">
      <% if current_user %>
        Logged as <%= link_to current_user.userName , current_user%>
      <% else %>
        <%= link_to 'Log In', root_path + "/auth/twitter"%>
      <% end %>
    </div>
  </div>
      <div class="content">
          <h4>New Submission</h4>

            <%= render 'form' %>
            
            <%= link_to submissions_path  , :class => "btn" do %>
                Back
            <% end %>
      </div>
    </div>
</div>

app/views/submissions/show.html.erb
<div class="submission">
  <div class="menu-superior">
    <%= link_to 'Hacker News', submissions_path %>
    <div class="right-text">
      <% if current_user %>
        Logged as <%= link_to current_user.userName , current_user%>
      <% else %>
        <%= link_to 'Log In', root_path + "/auth/twitter"%>
      <% end %>
    </div>
  </div>
  <div class="content">
    
    <div>
      <%= link_to "", like_submission_path(@submission), method: :put , :class => "upvote" %>
      <%= @submission.title %>
      <% if @submission.url != ""%>
        <a href= "<%= @submission.url %>" class="special-text">
          (<%= @submission.url %>)
        </a>
      <% end %>
      <% if current_user == @submission.user %>
        <%= link_to '[Edit]', edit_submission_path(@submission) %>
      <% end %>  
      <br> 
      <div class="submission-text">
        <%= @submission.get_upvotes.size %> points 
        by <%= link_to @submission.user.userName, @submission.user %>
        <%= @submission.created_at.to_formatted_s(:short) %>
      </div>
    </div>
    
    <p>
      <%= @submission.content %>
    </p>
    
    <% if current_user %>
      <%= form_for(@comment) do |f| %>
        <div class="field">
          <%= f.text_area :content %>
        </div>
        <input type="hidden" name="comment[user_id]" value="<%= current_user.id %>" />
        <input type="hidden" name="comment[submission_id]" value="<%= @submission.id %>" />
        <div class="actions">
          <%= f.submit %>
        </div>
      <% end %>
    <% end %>
    
    <p></p>
    
    <% @submission.comments.each do |comment| %>
      <%= link_to "", like_comment_path(comment), method: :put , :class => "upvote" %>
      <div class="special-text">
        <%= comment.get_upvotes.size %> points 
        by <%= link_to comment.user.userName, comment.user %>
        <%= comment.created_at.to_formatted_s(:short) %>
      </div><br>
      <%= comment.content %><br>
      <% if current_user %>
        <%= link_to '[Reply]', new_reply_path(:com_id => comment.id) %>
      <% end %>
      
      <% comment.replies.each do |reply| %>
        <div class="reply">
          <%= link_to "", like_reply_path(reply), method: :put , :class => "upvote" %>
          <div class="special-text">
            <%= reply.get_upvotes.size %> points
            by <%= link_to reply.user.userName, reply.user %>
            <%= reply.created_at.to_formatted_s(:short) %>
          </div><br>
          <%= reply.content %>
        </div>
        <p></p>
      <% end %>
      <p></p>
    <% end %>
    
    <p></p>
    <%= link_to submissions_path, :class => "btn" do %>
    Back
    <% end %>
  </div>
</div>